// getters
export const GET_CUR_SHOP_TODAY_SALES = 'GET_CUR_SHOP_TODAY_SALES';
export const GET_CUR_PRODUCT_TODAY_SALES = 'GET_CUR_PRODUCT_TODAY_SALES';
export const GET_CUR_PRODUCT_YESTERDAY_SALES = 'GET_CUR_PRODUCT_YESTERDAY_SALES';
export const GET_CUR_SHOP_PEROID_SALES = 'GET_CUR_SHOP_PEROID_SALES';

// mutations
export const MODIFY_CUR_SHOP_TODAY_SALES = 'MODIFY_CUR_SHOP_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_TODAY_SALES = 'MODIFY_CUR_PRODUCT_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_YESTERDAY_SALES = 'MODIFY_CUR_PRODUCT_YESTERDAY_SALES';
export const MODIFY_CUR_SHOP_PEROID_SALES = 'MODIFY_CUR_SHOP_PEROID_SALES';

// actions
export const LOAD_CUR_SHOP_TODAY_SALES = 'LOAD_CUR_SHOP_TODAY_SALES';
export const LOAD_CUR_PRODUCT_TODAY_SALES = 'LOAD_CUR_PRODUCT_TODAY_SALES';
export const LOAD_CUR_PRODUCT_YESTERDAY_SALES = 'LOAD_CUR_PRODUCT_YESTERDAY_SALES';
export const LOAD_CUR_SHOP_PEROID_SALES = 'LOAD_CUR_SHOP_PEROID_SALES';
