// getters
export const GET_CUR_SHOP_TODAY_SALES = 'GET_CUR_SHOP_TODAY_SALES';
export const GET_CUR_PRODUCT_TODAY_SALES = 'GET_CUR_PRODUCT_TODAY_SALES';
export const GET_CUR_PRODUCT_YESTERDAY_SALES = 'GET_CUR_PRODUCT_YESTERDAY_SALES';
export const GET_CUR_SHOP_PERIOD_SALES = 'GET_CUR_SHOP_PERIOD_SALES';
export const GET_PRODUCT_ONE_DAY_SALES = 'GET_PRODUCT_ONE_DAY_SALES';
export const GET_PRODUCT_PERIOD_SALES = 'GET_PRODUCT_PERIOD_SALES';
export const GET_ALL_SHOPS_TODAY_SALES = 'GET_ALL_SHOPS_TODAY_SALES';
export const GET_ALL_SHOPS_SALES_RANK = 'GET_ALL_SHOPS_SALES_RANK';

// mutations
export const MODIFY_CUR_SHOP_TODAY_SALES = 'MODIFY_CUR_SHOP_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_TODAY_SALES = 'MODIFY_CUR_PRODUCT_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_YESTERDAY_SALES = 'MODIFY_CUR_PRODUCT_YESTERDAY_SALES';
export const MODIFY_CUR_SHOP_PERIOD_SALES = 'MODIFY_CUR_SHOP_PERIOD_SALES';
export const MODIFY_PRODUCT_ONE_DAY_SALES = 'MODIFY_PRODUCT_ONE_DAY_SALES';
export const MODIFY_PRODUCT_PERIOD_SALES = 'MODIFY_PRODUCT_PERIOD_SALES';
export const MODIFY_ALL_SHOPS_TODAY_SALES = 'MODIFY_ALL_SHOPS_TODAY_SALES';
export const MODIFY_ALL_SHOPS_SALES_RANK = 'MODIFY_ALL_SHOPS_SALES_RANK';

// actions
export const LOAD_CUR_SHOP_TODAY_SALES = 'LOAD_CUR_SHOP_TODAY_SALES';
export const LOAD_CUR_PRODUCT_TODAY_SALES = 'LOAD_CUR_PRODUCT_TODAY_SALES';
export const LOAD_CUR_PRODUCT_YESTERDAY_SALES = 'LOAD_CUR_PRODUCT_YESTERDAY_SALES';
export const LOAD_CUR_SHOP_PERIOD_SALES = 'LOAD_CUR_SHOP_PERIOD_SALES';
export const LOAD_PRODUCT_ONE_DAY_SALES = 'LOAD_PRODUCT_ONE_DAY_SALES';
export const LOAD_PRODUCT_PERIOD_SALES = 'LOAD_PRODUCT_PERIOD_SALES';
export const LOAD_ALL_SHOPS_TODAY_SALES = 'LOAD_ALL_SHOPS_TODAY_SALES';
export const LOAD_ALL_SHOPS_SALES_RANK = 'LOAD_ALL_SHOPS_SALES_RANK';
export const UPDATE_PRODUCT_ONE_DAY_SALES = 'UPDATE_PRODUCT_ONE_DAY_SALES';
