// getters
export const GET_CUR_SHOP_TODAY_SALES = 'GET_CUR_SHOP_TODAY_SALES';
export const GET_CUR_PRODUCT_TODAY_SALES = 'GET_CUR_PRODUCT_TODAY_SALES';
export const GET_CUR_PRODUCT_YESTERDAY_SALES = 'GET_CUR_PRODUCT_YESTERDAY_SALES';
export const GET_CUR_SHOP_PEROID_SALES = 'GET_CUR_SHOP_PEROID_SALES';
export const GET_PRODUCT_ONE_DAY_SALES = 'GET_PRODUCT_ONE_DAY_SALES';

// mutations
export const MODIFY_CUR_SHOP_TODAY_SALES = 'MODIFY_CUR_SHOP_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_TODAY_SALES = 'MODIFY_CUR_PRODUCT_TODAY_SALES';
export const MODIFY_CUR_PRODUCT_YESTERDAY_SALES = 'MODIFY_CUR_PRODUCT_YESTERDAY_SALES';
export const MODIFY_CUR_SHOP_PEROID_SALES = 'MODIFY_CUR_SHOP_PEROID_SALES';
export const MODIFY_PRODUCT_ONE_DAY_SALES = 'MODIFY_PRODUCT_ONE_DAY_SALES';

// actions
export const LOAD_CUR_SHOP_TODAY_SALES = 'LOAD_CUR_SHOP_TODAY_SALES';
export const LOAD_CUR_PRODUCT_TODAY_SALES = 'LOAD_CUR_PRODUCT_TODAY_SALES';
export const LOAD_CUR_PRODUCT_YESTERDAY_SALES = 'LOAD_CUR_PRODUCT_YESTERDAY_SALES';
export const LOAD_CUR_SHOP_PEROID_SALES = 'LOAD_CUR_SHOP_PEROID_SALES';
export const LOAD_PRODUCT_ONE_DAY_SALES = 'LOAD_PRODUCT_ONE_DAY_SALES';
export const UPDATE_PRODUCT_ONE_DAY_SALES = 'UPDATE_PRODUCT_ONE_DAY_SALES';
