// getters
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_CUR_SHOP_PRODUCTS = 'GET_CUR_SHOP_PRODUCTS';

// mutations
export const MODIFY_ALL_PRODUCTS = 'MODIFY_ALL_PRODUCTS';
export const MODIFY_CUR_SHOP_PRODUCTS = 'MODIFY_CUR_SHOP_PRODUCTS';

// mutations
export const LOAD_ALL_PRODUCTS = 'LOAD_ALL_PRODUCTS';
export const LOAD_CUR_SHOP_PRODUCTS = 'LOAD_CUR_SHOP_PRODUCTS';
export const LOAD_CUR_SHOP_PRE_PRODUCTS = 'LOAD_CUR_SHOP_PRE_PRODUCTS';
