// getters
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_CUR_SHOP_PRODUCTS = 'GET_CUR_SHOP_PRODUCTS';
export const GET_CUR_PRODUCT = 'GET_CUR_PRODUCT';

// mutations
export const MODIFY_ALL_PRODUCTS = 'MODIFY_ALL_PRODUCTS';
export const MODIFY_CUR_SHOP_PRODUCTS = 'MODIFY_CUR_SHOP_PRODUCTS';
export const MODIFY_CUR_PRODUCT = 'MODIFY_CUR_PRODUCT';

// actions
export const LOAD_ALL_PRODUCTS = 'LOAD_ALL_PRODUCTS';
export const LOAD_CUR_SHOP_PRODUCTS = 'LOAD_CUR_SHOP_PRODUCTS';
export const LOAD_CUR_SHOP_PRE_PRODUCTS = 'LOAD_CUR_SHOP_PRE_PRODUCTS';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const LOAD_CUR_PRODUCT = 'LOAD_CUR_PRODUCT';
